### PR TITLE
[Feat] Delete user account

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

Delete user account from TwoopsTracker when requested (Depends on https://github.com/CodeForAfrica/TwoopsTracker/pull/58)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

N/A

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code

### CODE REVIEW

**Review by KobbyMmo — APPROVED** [review]
Looks good @kilemensi 

What happens to the public Lists and accounts? (for backend/business logic though)

**Comment by kilemensi** [comment]
> Looks good @kilemensi
> 
> What happens to the public Lists and accounts? (for backend/business logic though)

I think they remain but @esirK can you confirm that we don't cascade delete when owner is delete?

**Comment by KobbyMmo** [comment]
> I think they remain but @esirK can you confirm that we don't cascade delete when owner is delete?

If they remain, is it assigned to another account? incase it needs to be managed? @esirK

**Comment by esirK** [comment]
> > Looks good @kilemensi
> > What happens to the public Lists and accounts? (for backend/business logic though)
> 
> I think they remain but @esirK can you confirm that we don't cascade delete when owner is delete?

Right now we do [Cascade](https://github.com/CodeForAfrica/TwoopsTracker/blob/main/twoopstracker/twoops/models.py#L151). Lemme update that

**Comment by esirK** [comment]
But thinking about it @kilemensi, I think the User Lists should be cascaded. What shouldn't be is the Twitter accounts since they might belong to other users' lists?

**Comment by kilemensi** [comment]
> But thinking about it @kilemensi, I think the User Lists should be cascaded. What shouldn't be is the Twitter accounts since they might belong to other users' lists?

Yes, Twitter accounts have to be **kept** @esirK. The only reason I thought we _shouldn't_ cascade is because I remember we discussed or implemented ability to give access to a list to other users e.g. you create a (private) and give access to @KobbyMmo . If I'm misremembering things then yes, we should cascade otherwise cascading delete will cause issues here.

**Comment by esirK** [comment]
@kilemensi  the way we implemented 'Sharing' was by using `Teams` so maybe we should remove Cascading on Teams? Set the team owner to Null on delete?

**Comment by kilemensi** [comment]
> @kilemensi the way we implemented 'Sharing' was by using `Teams` so maybe we should remove Cascading on Teams? Set the team owner to Null on delete?

So Teams can own lists or lists are still owned at individual level @esirK ?

**Comment by esirK** [comment]
I see. Lists are still at individual level.
What do you suggest? We set List owner to Null? @kilemensi

**Comment by kilemensi** [comment]
> I see. Lists are still at individual level. What do you suggest? We set List owner to Null? @kilemensi

You're the product owner @esirK ... surprise us!

**Pull request merged**
