### PR TITLE
[Fix] Tweet card

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

 - [x] Ensure high-quality profile pic is used, and
 - [x] Match design.

This PR also fixes Storybook to work with Webpack 5.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

S

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by KhadijaMahanga — APPROVED** [review]
🎤 ⬇️  

@kilemensi  Whats with the webpack5? for storybook?

**Comment by kilemensi** [comment]
> microphone arrow_down rocket
> 
> @kilemensi Whats with the webpack5? for storybook?

In current `main`, **Storybook** is broken because **Nextjs** 12 uses **Webpack** `5` by default and **Storybook** `6` uses **Webpack** 4 by default...

**Storybook** `6.3` added [opt-in **Webpack** `5` support](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5)

**Review by nerdlet — APPROVED** [review]
@Kilemensi Looks good! 

Quick question? What happens to accounts with no images like this 👇🏽
Screenshot 2022-01-27 at 10 41 38
Could we maybe use owner screen initials  instead when the image is not available?

**Comment by kilemensi** [comment]
> @kilemensi Looks good!
> 
> Quick question? What happens to accounts with no images like this 👇🏽 Screenshot 2022-01-27 at 10 41 38 Could we maybe use owner screen name initials instead when the image is not available?

Question is how do you know if an image exists or doesn't @nerdlet? Remember you only have a string url to that image.

... Of course you could try to fetch the image first using `fetch` but that kind of seems like an overkill.

**Comment by nerdlet** [comment]
> > @kilemensi Looks good!
> > Quick question? What happens to accounts with no images like this 👇🏽 Screenshot 2022-01-27 at 10 41 38 Could we maybe use owner screen name initials instead when the image is not available?
> 
> Question is how do you know if an image exists or doesn't @nerdlet? Remember you only have a string url to that image.
> 
> ... Of course you could try to fetch the image first using `fetch` but that kind of seems like an overkill.

@kilemensi Ahhh, okay, okay...

**Pull request merged**
