### PR TITLE
Fix Footer

### PR DESCRIPTION
**Pull request by nerdlet**
## Description

  #180581696

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

Screenshot 2021-12-14 at 10 38 24

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by KobbyMmo — COMMENTED** [review]
@nerdlet just a quick review, These can be added from cms right? and will be added when we have the pages for them?
image

**Comment by nerdlet** [comment]
> @nerdlet just a quick review, These can be added from cms right? and will be added when we have the pages for them? image



> @nerdlet just a quick review, These can be added from cms right? and will be added when we have the pages for them? image

Yap, we currently dont have the above pages...but when we do we can add them in the cms

**Review by KobbyMmo — APPROVED** [review]
Looks good to me @nerdlet

**Review by gertie-sheshe — APPROVED** [review]
LGTM @nerdlet

**Pull request merged**
