### PR TITLE
[Fix] Disable image optimization

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

This PR disables image optimization across the site.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

S

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by KobbyMmo — COMMENTED** [review]
I am not very sure whether the optimization provided by Nextjs was bad or we were just using smaller sized images @kilemensi

**Comment by kilemensi** [comment]
> I am not very sure whether the optimization provided by Nextjs was bad or we were just using smaller sized images @kilemensi

You can pull it locally and test @KobbyMmo

**Review by nerdlet — APPROVED** [review]
@kilemensi 🚀

**Review by nerdlet — APPROVED** [review]
@kilemensi 🚀

**Review by KobbyMmo — APPROVED** [review]

**Pull request merged**
